# Site settings
author: Seth Near
title: Flatiron Software Engineering Bootcamp
header-img: img/home-bg.png
email: seth.j.near@gmail.com
copyright_name: Seth Near
description: > # this means to ignore newlines until "baseurl:"
  Making the switch from hardware to software
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Never2Far

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
